# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d551e25ad4d74f32c956f75b3103ca71c0dd628e2cc907ab631ef8d75b57c50f436d2c3ae34b8cb7755935d88e8b98a7227617220056112783b9227d8871740

test:
  secret_key_base: 13fcf28aaa8a22a9a1293b6e051800074fb7c5db77f3af8c1472203db13d07b3688b4091cfc80895106c026308f91cf41f1e6ef1bb20d129bc86751563071a95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
